Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
